framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

    messenger:
        failure_transport: failed

        transports:
            # Sync is used for testing and development
            sync: 'sync://'

            # RabbitMQ transport for async messages
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages: ~

            # Failed messages transport
            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route messages to transports
            'App\Message\NewsCreatedNotification': async
            'App\Message\SimulateExternalAuthCheck': async


# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
