
services:
  nginx:
    image: nginx:${NGINX_VERSION:-1.21}-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    build:
      context: ./.docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"     # порт AMQP
      - "15672:15672"   # веб-интерфейс
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
###> doctrine/doctrine-bundle ###
  postgres:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-db}
      POSTGRES_USER: ${POSTGRES_USER:-db}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

